### PR TITLE
Feature/user profile

### PR DESCRIPTION
**Pull request by billfeng**

### CODE REVIEW

**Comment by GameKyuubi** [comment]
@bill-feng make sure to link to the user profile page when the user clicks on their name in the header

**Comment by billfeng** [comment]
@GameKyuubi Sure, I'll do that once the UI PR is merged! For now, is the rest of this PR good?

**Comment by GameKyuubi** [comment]
@bill-feng yep, everything else seems fine

**Comment by kumilange** [comment]
@bill-feng LGTM! 👍

**Review by kumilange — APPROVED** [review]

**Pull request merged**
