### PR TITLE
Feature/correct price

### LINKED ISSUE #91: Payment should be the same price as event price

### PR DESCRIPTION
**Pull request by billfeng**
Transactions are now charged based their event price, not a fixed 1000.
fixes #91

### CODE REVIEW

**Comment by kumilange** [comment]
@bill-feng LGTM! 👍

**Comment by billfeng** [comment]
@kumiko-haraguchi san if it's good could you approve it? thx!

**Comment by kumilange** [comment]
@bill-feng I think this needs to be reviewed by Mike as well :)

**Review by GameKyuubi — APPROVED** [review]
LGTM!
[LGTM](http://www.lgtm.in/i/o8USHMeTs)

[:+1:](http://www.lgtm.in/u/o8USHMeTs) [:-1:](http://www.lgtm.in/r/o8USHMeTs)

**Pull request merged**
